/* tslint:disable */
/* eslint-disable */
/**
 * Fullstack
 * API für das Fullstack Projekt
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Answer } from './answer';
 /**
 * 
 *
 * @export
 * @interface AnswerArray
 */
export interface AnswerArray extends Array<Answer> {
}
