/* tslint:disable */
/* eslint-disable */
/**
 * Fullstack
 * API für das Fullstack Projekt
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Answer
 */
export interface Answer {

    /**
     * @type {string}
     * @memberof Answer
     * @example 12345
     */
    id?: string;

    /**
     * @type {string}
     * @memberof Answer
     * @example 12345
     */
    questionId?: string;

    /**
     * @type {string}
     * @memberof Answer
     * @example Eine unglaublich hilfreiche und gut geschriebene Antwort
     */
    body?: string;

    /**
     * @type {Date}
     * @memberof Answer
     * @example 2024-11-08T12:34:56Z
     */
    createdAt?: Date;

    /**
     * @type {Date}
     * @memberof Answer
     * @example 2024-11-08T12:34:56Z
     */
    updatedAt?: Date;

    /**
     * @type {string}
     * @memberof Answer
     * @example 12345
     */
    userId?: string;

    /**
     * Anzahl der Stimmen
     *
     * @type {number}
     * @memberof Answer
     * @example 420
     */
    votes?: number;
}
