/* tslint:disable */
/* eslint-disable */
/**
 * Fullstack
 * API für das Fullstack Projekt
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateAnswer
 */
export interface CreateAnswer {

    /**
     * Der Inhalt der Antwort
     *
     * @type {string}
     * @memberof CreateAnswer
     * @example Eine unglaublich hilfreiche und gut geschriebene Antwort
     */
    body: string;
}
