/* tslint:disable */
/* eslint-disable */
/**
 * Fullstack
 * API für das Fullstack Projekt
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateQuestion
 */
export interface CreateQuestion {

    /**
     * @type {string}
     * @memberof CreateQuestion
     * @example Wie schreibe ich eine Fullstack Webanwendung?
     */
    title: string;

    /**
     * @type {string}
     * @memberof CreateQuestion
     * @example Bitte helft mir das Modul ist so schwer!
     */
    body: string;
}
