/* tslint:disable */
/* eslint-disable */
/**
 * Fullstack
 * API für das Fullstack Projekt
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateUser
 */
export interface CreateUser {

    /**
     * @type {string}
     * @memberof CreateUser
     * @example MaxMustermann123
     */
    username: string;

    /**
     * @type {string}
     * @memberof CreateUser
     * @example maxmustermann@gmail.com
     */
    email: string;

    /**
     * @type {string}
     * @memberof CreateUser
     * @example passwort123
     */
    password: string;
}
