/* tslint:disable */
/* eslint-disable */
/**
 * Fullstack
 * API für das Fullstack Projekt
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {

    /**
     * @type {string}
     * @memberof ErrorResponse
     * @example User mit der ID 12345 nicht gefunden!
     */
    error?: string;

    /**
     * Errorstatuscode
     *
     * @type {number}
     * @memberof ErrorResponse
     * @example 404
     */
    code?: number;
}
