/* tslint:disable */
/* eslint-disable */
/**
 * Fullstack
 * API für das Fullstack Projekt
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse403
 */
export interface InlineResponse403 {

    /**
     * @type {string}
     * @memberof InlineResponse403
     * @example Keine Berechtigung, diese Frage zu löschen.
     */
    error?: string;

    /**
     * @type {number}
     * @memberof InlineResponse403
     * @example 403
     */
    code?: number;
}
