/* tslint:disable */
/* eslint-disable */
/**
 * Fullstack
 * API für das Fullstack Projekt
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse401
 */
export interface InlineResponse401 {

    /**
     * @type {string}
     * @memberof InlineResponse401
     * @example E-Mail oder Passwort ungültig
     */
    error?: string;

    /**
     * @type {number}
     * @memberof InlineResponse401
     * @example 401
     */
    code?: number;
}
