/* tslint:disable */
/* eslint-disable */
/**
 * Fullstack
 * API für das Fullstack Projekt
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse2001
 */
export interface InlineResponse2001 {

    /**
     * @type {string}
     * @memberof InlineResponse2001
     * @example Benutzer erfolgreich gelöscht
     */
    message?: string;
}
