/* tslint:disable */
/* eslint-disable */
/**
 * Fullstack
 * API für das Fullstack Projekt
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpdateQuestion
 */
export interface UpdateQuestion {

    /**
     * @type {string}
     * @memberof UpdateQuestion
     * @example Wie schreibe ich eine Fullstack Webanwendung, die mir eine 1,0 bringt?
     */
    title?: string;

    /**
     * @type {string}
     * @memberof UpdateQuestion
     * @example Bitteh helft mir die Deadline ist morgen!
     */
    body?: string;
}
