/* tslint:disable */
/* eslint-disable */
/**
 * Fullstack
 * API für das Fullstack Projekt
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface VoteResponse
 */
export interface VoteResponse {

    /**
     * Die ID des bewerteten Elements
     *
     * @type {string}
     * @memberof VoteResponse
     */
    id?: string;

    /**
     * Die neue Anzahl der Stimmen
     *
     * @type {number}
     * @memberof VoteResponse
     */
    votes?: number;
}
